seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/listings.rb
    page_type: listings
    disabled: false
  - file: ./parsers/products.rb
    page_type: products
    disabled: false

exporters:
  - exporter_name: products_walmart_movie_json
    exporter_type: json
    collection: products
    write_mode: pretty_array
    start_on_job_done: true
    